### ISSUE TITLE
Learning mode i SImulation mode

### ISSUE THREAD

**Issue by yotf** [yotf/CancerModel#5]
Postojace dva mode-a pustanja simulacije:
* Learning-mode (ovde se pusta da agenti evoluiraju u nedogled, tj. dok ne bude 10 koraka da se fitness funkcija nije promenila za 10)
* Real-life mode : pustaju se nanoagenti iz labaratorije u zivot, gde ce ustvari imati ograniceno vreme da delaju, tj. umrece nakon 10*30 koraka npr.

**Comment by yotf** [comment]
Agenti se cuvaju u CSV i prosledjuju medju-skripti.
Medju-skripta ce uzeti rezultate simulacije (u vidu nanoagenata i njihovih krajnjih svojstava) i napraviti populacije za pustanje u real-life.  Detaljniji opis medju-skripte je u #6 

Real-life rezim ce umesto generisanja novih agenate ni iz cega, ih generisati iz csv fajla. 
Osim toga, razlika real-life rezima je ogranicenost vremena i ne postoji mogucnost promene (mutacije, dupliciranja, izumiranja) agenata. 

@Sommnium Kad umru nano-agenti - simulacija nastavlja bez njih? Da li ce se reinjektovati?

**Comment by yotf** [comment]
Learning-mode prestaje posle 10*10*10 koraka. 
U simulation-mode, svaka cestica koje se asocirala ce da umre, tj. nece se vracati u kretanje (bila uspesna ili ne ) .
Ako ne umre tako, umrece posle nekog vremensko perioda (decay rate). Injektovanje novih cestica ce se desiti ako ne postoji vise nijedan nanoagent.

**Comment by Sommnium** [comment]
> Injektovanje novih cestica ce se desiti ako ne postoji vise nijedan nanoagent.

to treba da bude opciono uz proizvoljan time delay

**Comment by yotf** [comment]
"ubacujemo prvih 20 sati (14
vremenskih koraka) tako da njihov broj linearno raste do maksimuma (ako
ih ima 500 onda svaki vremenski korak dodajemo po 35 NA, pa tako 14
koraka) i onda tempiramo decay rate tako da linearno opada njihov broj
sledecih 80 sati (58 koraka)."

"kada
dobijemo rezultate prvog modula i ubacujemo u simulation module ne treba
da variramo decay rate vec samo maksimalan broj agenata koji cemo
injektovati. Ako cemo da se drzimo 5 varijanti onda bi samo razlika bila
u tome da ukupno injektujemo 100, 200,300,400 i 500 agenata (i ako
kazemo da max treba da bude nakon 20 sati onda u svakom vremenskom
koraku injektujemo 1/20 tog broja)."

**Comment by yotf** [comment]
@Sommnium 
Iz learning-mode dobijamo 500 agenata, i onda selektujemo 100,200,300,400,500 za simulation-mode tako sto uzmemo prvih *n* stavki u rezultatima learning-mode-a?

**Comment by Sommnium** [comment]
pitas za ono kada odabiramo top n stavki?
Ako je to onda uzmemo npr top 3 stavke i normalizujemo njihovu brojnost na 100, 200, 300, 400, 500.
npr ako su top 3 iz learning mode 27,15,8 (sum = 50) onda ce normalizacija na 100 biti: 
27*(100/50), 15*(100/50), 8*(100/50).
Normalizacija na 200=
27*(200/50), 15*(200/50), 8*(200/50)...

**Comment by yotf** [comment]
Aha, da, onda ce se to sve desavati u klasifikaciji.
Znaci klasifikacija nam (iz jednog rezultata) daje 10 novih fajlova.
5 sa celom populacijom, 5 sa top3. 
Ako radimo sa celom populacijom, onda samo odsecem na 100,200,300,400,500 prvih zapisa?
U learning mode uvek ostajemo pri broju 500 agenata?

**Comment by Sommnium** [comment]
> U learning mode uvek ostajemo pri broju 500 agenata?
da
> Ako radimo sa celom populacijom, onda samo odsecem na 100,200,300,400,500 prvih zapisa?
mislim da je to jajjednostavnije

**Comment by yotf** [comment]
@Sommnium  Da li nanoagenti imaju mogucnost da umru (decay) pre nego sto se svi injektuju? Tj. da li krece od prvog koraka ta mogucnost ili od  14og?

**Comment by Sommnium** [comment]
dobro pitanje. Ako cemo da budemo sto blize stvarnosti - onda da. Ne znam da li ima nekih posebnih posledica
